name: "CI"
on: ["push", "pull_request"]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: WillAbides/setup-go-faster@v1.7.0
        with:
          go-version: 1.22
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1.1"
          cache-key: 1.22
      - run: staticcheck ./helper
